---
title: "project3"
author: "Mehdi Khan"
date: "October 2, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressMessages(suppressWarnings(library(ggplot2)))
suppressMessages(suppressWarnings(library(leaflet)))
suppressMessages(suppressWarnings(library(maps)))
suppressMessages(suppressWarnings(library(shiny)))
suppressMessages(suppressWarnings(library(sp)))
suppressMessages(suppressWarnings(library(plotly)))
#suppressMessages(suppressWarnings(library(geojsonio)))
#suppressMessages(suppressWarnings(library(rgdal)))
```

http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html

https://www.datascience.com/blog/beginners-guide-to-shiny-and-leaflet-for-interactive-mapping

```{r}
mortData <- read.csv("./data/cleaned-cdc-mortality-1999-2010-2.csv",sep = ",", stringsAsFactors = FALSE)
stategeo <- read.csv("./data/statelatlong.csv",sep = ",", stringsAsFactors = FALSE)
```


f <- function(DS, x, y) {    
  ggplot(DS, aes_string(x = x, y = y)) + geom_point()  
}
And then call the function as:

f(cars, "speed", "dist")


```{r}
causes <- unique(mortData$ICD.Chapter)
States <- mortData$State
mapStates <- map("state", fill = TRUE, plot = FALSE)

mortData$lat <- stategeo[match(mortData$State,stategeo$State),2]
mortData$long <- stategeo[match(mortData$State,stategeo$State),3]
mortData$StateFull <- stategeo[match(mortData$State,stategeo$State),4]
```



```{r}
ui <-fluidPage(
  div(style = "color:blue,vertical-align:middle",
  # pageWithSidebar(
  # headerPanel("Data 608, Project3, Mehdi Khan"),
  titlePanel("Data 608, Project3, Mehdi Khan"),
  fluidRow(
   
   column(width = 12,align='center',
     
    tabsetPanel(
      tabPanel("Question1", value=1, 
               fluidRow(
                 uiOutput("selectCause"),
                 column(6,
                      conditionalPanel( condition = "output.rowno==0",
                           verbatimTextOutput("noresult")),
                            tags$head(tags$style("#noresult{color: red;
                                 font-size: 15px;
                                 font-style: bold;
                                 }"              
                                                )
                                     ),
                      conditionalPanel(condition = "output.rowno==1",
                       plotlyOutput("Question1")) 
                    ),
                  column(6,
                      leafletOutput("ratemap",height = 350)
                    )
               
                      )
                  ),
      
      tabPanel("Question2", value=2,
                fluidRow(
                 uiOutput("selectState")
                 )), 
      id = "tabselected"
      )
   )
  )
  )
  
  
  
 
  
  
  
#    sidebarPanel(
#     conditionalPanel(condition="input.tabselected==1",uiOutput("selectCause")),
#     conditionalPanel(condition="input.tabselected==2",uiOutput("selectState"))
# 
# 
#   ),
#   mainPanel(
#      
#      verbatimTextOutput("var"),
#     tabsetPanel(
#       tabPanel("Question1", value=1, plotOutput("Question1") ),
#       
#       tabPanel("Question2", value=2), 
#       id = "tabselected"
#       )
#     )
   # )
 )

  
  server <- function(input,output){
    
     # populate the list of causes
  output$selectCause <- renderUI({selectInput("causes", "select a cause", choices=causes, width = 600)
  })
  # populate the list of States
  output$selectState <- renderUI({ selectInput("states", "select a State", choices=States)
  })
   
    variable <- reactive({input$causes}) 
    variable2 <- reactive({input$states})
   output$var <- renderPrint({variable2()})
   
    output$rowno <- reactive(if (nrow(mortData[mortData$Year==2010 & mortData$ICD.Chapter==variable(),])==0) 0 else 1)
  
    #output$noresult <- renderUI({if (rowno()== 0) {textInput("label", txt())} else NULL })
      
   output$noresult <- renderText({
     cause <- req(variable())
     if (nrow(mortData[mortData$Year==2010 & mortData$ICD.Chapter==cause,])==0){
       txt <- paste("No record for ",cause,"in the year of 2010", sep = " ")}
       txt
   })
   
   
   output$Question1 <- renderPlotly({ 
     
     cause <- req(variable())
     # if (nrow(mortData[mortData$Year==2010 & mortData$ICD.Chapter==cause,])==0){
     #   txt <- paste("No record for ",cause,"in the year of 2010", sep = " ")
     #   output$noresult <- renderText({txt})
     #   ggplot(NULL)
     # }
     # else {
     mortRate(cause)}#}
     )
   
   
   
     output$ratemap <- renderLeaflet({
     df <- mortData[mortData$Year==2010 & mortData$ICD.Chapter==variable(),]
     bins <- c(0, 5, 10, 15, 20, 25, 30, 35, max( df$Crude.Rate))
     pal <- colorBin("YlOrRd", domain = df$Crude.Rate, bins = bins)

   m <- leaflet(data = df) %>%
          addTiles(options=providerTileOptions(noWrap = TRUE)) %>%
          setView(lng=-95.60095789311049, lat=40.2788930072988 , zoom=3) %>%
     
          addPolygons(lng = mapStates$x, 
                      lat = mapStates$y, 
                      #fillColor = topo.colors(10, alpha = NULL), 
                      fillColor = ~pal(Crude.Rate), 
                      stroke = FALSE) %>% 
         addMarkers (lng = ~long,
                     lat = ~lat,
                     popup = paste("Crude Rate:", df$Crude.Rate, "<br>",
                                    "State:", df$StateFull, "<br>",
                                   "Year:", "2010"))
   
   
 })
 outputOptions(output, "rowno", suspendWhenHidden = FALSE)   
    
  }

``` 
  
  
```{r}

mortRate <- function(disease){
df <- mortData[mortData$Year==2010 & mortData$ICD.Chapter==disease,]
df$State <- factor(df$State, levels = df[order(-df$Crude.Rate),"State"])
p <- ggplot(df,aes(State,Crude.Rate))+geom_point(size = 3)+geom_segment(aes(x=State,xend=State, y=0,yend=Crude.Rate))+labs( x="State")+theme(axis.text.x = element_text(angle = 90,vjust = 0.25, size = 8))

ggplotly(p) %>% config(displaylogo = FALSE,
modeBarButtonsToRemove = list(
    'sendDataToCloud',
    'toImage',
    'autoScale2d',
    'resetScale2d',
    'hoverClosestCartesian',
    'hoverCompareCartesian'
))
  
}

# mortRate <- function(disease){
# df <- mortData[mortData$Year==2010 & mortData$ICD.Chapter==disease,]
# df <- df[with(df,order(-Crude.Rate)),]
# ggplot(df,aes(reorder(State,-Crude.Rate),Crude.Rate))+geom_point(size = 3)+geom_segment(aes(x=reorder(State,-Crude.Rate),xend=reorder(State,-Crude.Rate), y=0,yend=Crude.Rate))+labs( x="State")+theme(axis.text.x = element_text(angle = 90,vjust = 0.25, size = 8))
# 
#   
# }

# ggplot(mortData[mortData$Year==2010 & mortData$ICD.Chapter=='Certain infectious and parasitic diseases',],aes(reorder(State,-Crude.Rate),Crude.Rate))+geom_point(size = 3)+geom_segment(aes(x=reorder(State,-Crude.Rate),xend=reorder(State,-Crude.Rate), y=0,yend=Crude.Rate))+labs(title="Mortality Rate By State", x="State")+theme(axis.text.x = element_text(angle = 90,vjust = 0.25, size = 8))

#mortRate("External causes of morbidity and mortality"  )
library(dplyr)
mypick <- "Certain infectious and parasitic diseases"
mypick <- "Neoplasms"
sub2 <- mortData %>% filter(ICD.Chapter==mypick) %>%
    select(State, Year, Deaths, Population, Crude.Rate) %>%
    group_by(Year) %>%
    mutate(Nat.Avg = round((sum(Deaths) / sum(Population)) * 10^5, 1)) %>%
    select(State, Year, Crude.Rate, Nat.Avg) %>%
    ungroup()

sub2$State <- as.character(sub2$State)

ggplot(sub2[sub2$State=='AZ',],aes(Year))+geom_line(aes(y=Crude.Rate,colour="al"))+geom_line(aes(y=Nat.Avg,colour="us"))

```



```{r}
#states <- geojsonio::geojson_read("json/us-states.geojson", what = "sp")
```



```{r}
# library(raster)
# library(leaflet)
# 
# usa <- getData("GADM", country="USA", level=2)
# usa$randomData <- rnorm(n=nrow(usa), 150, 30)
# 
# #create a color palette to fill the polygons
# pal <- colorQuantile("Greens", NULL, n = 5)
# 
# #create a pop up (onClick)
# polygon_popup <- paste0("<strong>Name: </strong>", usa$NAME_1, "<br>",
#                         "<strong>Indicator: </strong>", round(usa$randomData,2))
# 
# #create leaflet map
#   map = leaflet() %>% 
#       addProviderTiles("CartoDB.Positron") %>% 
#       setView(-98.35, 39.7,
#               zoom = 4) %>% 
#       addPolygons(data = usa, 
#                   fillColor= ~pal(randomData),
#                   fillOpacity = 0.4, 
#                   weight = 2, 
#                   color = "white",
#                   popup = polygon_popup)
# map

```



  
```{r}
 
  shinyApp(ui=ui, server = server) 

```



